#!/bin/bash
################################################################################
# Quick Reference: Wormhole Fix Validation
################################################################################

echo "=============================================================================="
echo "WORMHOLE FIX VALIDATION - QUICK REFERENCE"
echo "=============================================================================="
echo ""

echo "FILES TO TRANSFER TO LINUX VM:"
echo "------------------------------"
echo "1. routing.cc                      (Modified: Deterministic selection)"
echo "2. test_wormhole_focused.sh        (New: 30-node focused test)"
echo "3. analyze_wormhole_focused.py     (New: Analysis with latency)"
echo "4. analyze_wormhole_issues.py      (New: Diagnostic tool)"
echo ""

echo "STEP 1: REBUILD NS-3"
echo "------------------------------"
echo "cd ~/ns-allinone-3.35/ns-3.35"
echo "cp /path/to/routing.cc scratch/"
echo "./ns3 clean"
echo "./ns3 build"
echo ""

echo "STEP 2: RUN FOCUSED TEST (~30 minutes)"
echo "------------------------------"
echo "chmod +x test_wormhole_focused.sh"
echo "./test_wormhole_focused.sh"
echo ""
echo "Expected Results:"
echo "  - 16 tests completed"
echo "  - Results in: wormhole_evaluation_YYYYMMDD_HHMMSS/"
echo ""

echo "STEP 3: ANALYZE RESULTS"
echo "------------------------------"
echo "python3 analyze_wormhole_focused.py wormhole_evaluation_YYYYMMDD_HHMMSS/"
echo ""
echo "Generated Files:"
echo "  1. pdr_latency_vs_attack_percentage.png"
echo "  2. tunnel_analysis.png"
echo "  3. latency_breakdown.png"
echo "  4. wormhole_analysis_summary.txt"
echo ""

echo "STEP 4: VERIFY FIXES"
echo "------------------------------"
echo "Check tunnel_analysis.png:"
echo "  Expected Tunnels (30 nodes): 2, 4, 6, 8, 10 (for 20-100%)"
echo ""
echo "Check wormhole_analysis_summary.txt:"
echo "  - Tunnel counts match expected"
echo "  - Latency metrics populated"
echo "  - Mitigation shows latency reduction"
echo ""

echo "EXPECTED TUNNEL COUNTS:"
echo "------------------------------"
echo "30 nodes (20 vehicles + 10 RSUs):"
echo "  20% -> 4 vehicles -> 2 tunnels"
echo "  40% -> 8 vehicles -> 4 tunnels"
echo "  60% -> 12 vehicles -> 6 tunnels"
echo "  80% -> 16 vehicles -> 8 tunnels"
echo "  100% -> 20 vehicles -> 10 tunnels"
echo ""
echo "70 nodes (60 vehicles + 10 RSUs):"
echo "  20% -> 12 vehicles -> 6 tunnels"
echo "  40% -> 24 vehicles -> 12 tunnels"
echo "  60% -> 36 vehicles -> 18 tunnels"
echo "  80% -> 48 vehicles -> 24 tunnels"
echo "  100% -> 60 vehicles -> 30 tunnels"
echo ""

echo "TROUBLESHOOTING:"
echo "------------------------------"
echo "If tunnels still show 4 for all percentages:"
echo "  1. Check routing.cc was copied correctly"
echo "  2. Verify clean rebuild (./ns3 clean; ./ns3 build)"
echo "  3. Check simulation logs for attacker selection messages"
echo "  4. Run diagnostic: python3 analyze_wormhole_issues.py <results_dir>"
echo ""

echo "SUCCESS CRITERIA:"
echo "------------------------------"
echo "✅ Tunnel count increases with attack percentage"
echo "✅ Active tunnels scale with intensity"
echo "✅ Latency metrics show wormhole vs normal differences"
echo "✅ Mitigation reduces latency (route changes)"
echo "✅ Graphs show clear trends"
echo ""

echo "NEXT STEPS AFTER VALIDATION:"
echo "------------------------------"
echo "1. Run comprehensive evaluation (70 nodes, 76 tests):"
echo "   ./test_sdvn_complete_evaluation.sh"
echo ""
echo "2. Run validation suite (all fixes):"
echo "   ./validate_fixes.sh"
echo ""
echo "3. Generate publication graphs:"
echo "   python3 analyze_comprehensive_evaluation.py <results_dir>"
echo ""

echo "=============================================================================="
echo "For detailed information, see: WORMHOLE_FIX_SUMMARY.md"
echo "=============================================================================="
